
package com.sippulse.soapadapter.sippulse.client.didWS;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DidWS", targetNamespace = "http://service.ws.sippulse.voffice.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DidWS {


    /**
     * 
     * @param didId
     * @param principal
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDid", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.DeleteDid")
    @ResponseWrapper(localName = "deleteDidResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.DeleteDidResponse")
    public void deleteDid(
        @WebParam(name = "didId", targetNamespace = "")
        Integer didId,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "did", targetNamespace = "")
    @RequestWrapper(localName = "listAvailablesNumbers", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.ListAvailablesNumbers")
    @ResponseWrapper(localName = "listAvailablesNumbersResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.ListAvailablesNumbersResponse")
    public List<String> listAvailablesNumbers(
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param did
     * @param principal
     * @return
     *     returns java.lang.Integer
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "didId", targetNamespace = "")
    @RequestWrapper(localName = "insertDid", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.InsertDid")
    @ResponseWrapper(localName = "insertDidResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.InsertDidResponse")
    public Integer insertDid(
        @WebParam(name = "did", targetNamespace = "")
        Did did,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param accountCode
     * @param principal
     * @return
     *     returns java.util.List<com.sippulse.soapadapter.sippulse.client.didWS.Did>
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "did", targetNamespace = "")
    @RequestWrapper(localName = "listByAcc", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.ListByAcc")
    @ResponseWrapper(localName = "listByAccResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.didWS.ListByAccResponse")
    public List<Did> listByAcc(
        @WebParam(name = "accountCode", targetNamespace = "")
        String accountCode,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

}
