spring:
  application:
    name: soapadapter

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

sippulse:
  auth:
    login: ${USER_ADMIN}
    password: ${PASSWORD_ADMIN}

soap:
  endpoints:
    domain: ${URL}/SipPulse/DomainWS
    profile: ${URL}/SipPulse/ProfileWS
    subscriber: ${URL}/SipPulse/SubscriberWS
    did: ${URL}/SipPulse/DidWS
    whitelist: ${URL}/SipPulse/WhiteListWS
    ratePlan: ${URL}/SipPulse/RatePlanWS
    rate: ${URL}/SipPulse/RateWS
    accountGroup: ${URL}/SipPulse/AccountGroupWS
    customer: ${URL}/SipPulse/CustomerWS
    userLocation: ${URL}/SipPulse/UserLocationWS
    address: ${URL}/SipPulse/AddressWS
    huntGroup: ${URL}/SipPulse/HuntGroupWS
    reloadModule: ${URL}/SipPulse/ReloadModulesWS

logging:
  level:
    com.sun.xml.ws: ERROR