
package com.sippulse.soapadapter.sippulse.client.reloadWS;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReloadModulesWS", targetNamespace = "http://service.ws.sippulse.voffice.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReloadModulesWS {


    /**
     * 
     * @param domain
     * @param principal
     * @param profile
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "reloadProfile", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadProfile")
    @ResponseWrapper(localName = "reloadProfileResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadProfileResponse")
    public void reloadProfile(
        @WebParam(name = "profile", targetNamespace = "")
        String profile,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "reloadSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadSubscriber")
    @ResponseWrapper(localName = "reloadSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadSubscriberResponse")
    public void reloadSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param didId
     * @param principal
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "reloadDid", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadDid")
    @ResponseWrapper(localName = "reloadDidResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadDidResponse")
    public void reloadDid(
        @WebParam(name = "didId", targetNamespace = "")
        Integer didId,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "reloadAddress", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadAddress")
    @ResponseWrapper(localName = "reloadAddressResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadAddressResponse")
    public void reloadAddress(
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param huntGroupId
     * @param principal
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "reloadHuntGroup", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadHuntGroup")
    @ResponseWrapper(localName = "reloadHuntGroupResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.reloadWS.ReloadHuntGroupResponse")
    public void reloadHuntGroup(
        @WebParam(name = "huntGroupId", targetNamespace = "")
        Integer huntGroupId,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

}
