
package com.sippulse.soapadapter.sippulse.client.reloadWS;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "WSException", targetNamespace = "http://service.ws.sippulse.voffice.com.br/")
public class WSException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WsExceptionMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSException(String message, WsExceptionMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public WSException(String message, WsExceptionMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sippulse.soapadapter.sippulse.client.reloadWS.WsExceptionMessage
     */
    public WsExceptionMessage getFaultInfo() {
        return faultInfo;
    }

}
