
package com.sippulse.soapadapter.sippulse.client.subscriberWS;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SubscriberWS", targetNamespace = "http://service.ws.sippulse.voffice.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubscriberWS {


    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockEntry0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockEntry0303")
    @ResponseWrapper(localName = "blockEntry0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockEntry0303Response")
    public void blockEntry0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns java.lang.String
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrievePassword", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrievePassword")
    @ResponseWrapper(localName = "retrievePasswordResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrievePasswordResponse")
    public String retrievePassword(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns java.lang.String
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrievePasswordWEB", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrievePasswordWEB")
    @ResponseWrapper(localName = "retrievePasswordWEBResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrievePasswordWEBResponse")
    public String retrievePasswordWEB(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriberClassV", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberClassV")
    @ResponseWrapper(localName = "updateSubscriberClassVResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberClassVResponse")
    public void updateSubscriberClassV(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberClassVDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriberBillingInfo", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberBillingInfo")
    @ResponseWrapper(localName = "updateSubscriberBillingInfoResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberBillingInfoResponse")
    public void updateSubscriberBillingInfo(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberBillingInfoDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriberServices", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberServices")
    @ResponseWrapper(localName = "updateSubscriberServicesResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberServicesResponse")
    public void updateSubscriberServices(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberServicesDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns com.sippulse.soapadapter.sippulse.client.subscriberWS.SubscriberDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveSubscriber")
    @ResponseWrapper(localName = "retrieveSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveSubscriberResponse")
    public SubscriberDTO retrieveSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns com.sippulse.soapadapter.sippulse.client.subscriberWS.SubscriberClassVDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveSubscriberClassV", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveSubscriberClassV")
    @ResponseWrapper(localName = "retrieveSubscriberClassVResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveSubscriberClassVResponse")
    public SubscriberClassVDTO retrieveSubscriberClassV(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateIncommingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateIncommingCalls")
    @ResponseWrapper(localName = "activateIncommingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateIncommingCallsResponse")
    public void activateIncommingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockIncommingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockIncommingCalls")
    @ResponseWrapper(localName = "blockIncommingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockIncommingCallsResponse")
    public void blockIncommingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateOutgoingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateOutgoingCalls")
    @ResponseWrapper(localName = "activateOutgoingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateOutgoingCallsResponse")
    public void activateOutgoingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockOutgoingCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockOutgoingCalls")
    @ResponseWrapper(localName = "blockOutgoingCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockOutgoingCallsResponse")
    public void blockOutgoingCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateCallsOnlyByIp", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateCallsOnlyByIp")
    @ResponseWrapper(localName = "activateCallsOnlyByIpResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateCallsOnlyByIpResponse")
    public void activateCallsOnlyByIp(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockCallsOnlyByIp", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockCallsOnlyByIp")
    @ResponseWrapper(localName = "blockCallsOnlyByIpResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockCallsOnlyByIpResponse")
    public void blockCallsOnlyByIp(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateCollectCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateCollectCalls")
    @ResponseWrapper(localName = "activateCollectCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateCollectCallsResponse")
    public void activateCollectCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateAnonymousCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateAnonymousCalls")
    @ResponseWrapper(localName = "activateAnonymousCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateAnonymousCallsResponse")
    public void activateAnonymousCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activatePrivacyCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivatePrivacyCalls")
    @ResponseWrapper(localName = "activatePrivacyCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivatePrivacyCallsResponse")
    public void activatePrivacyCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockPrivacyCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockPrivacyCalls")
    @ResponseWrapper(localName = "blockPrivacyCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockPrivacyCallsResponse")
    public void blockPrivacyCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param lowCreditLimit
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateLowCreditNotification", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateLowCreditNotification")
    @ResponseWrapper(localName = "activateLowCreditNotificationResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateLowCreditNotificationResponse")
    public void activateLowCreditNotification(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "lowCreditLimit", targetNamespace = "")
        Double lowCreditLimit,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockLowCreditNotification", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockLowCreditNotification")
    @ResponseWrapper(localName = "blockLowCreditNotificationResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockLowCreditNotificationResponse")
    public void blockLowCreditNotification(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateDailyStatistics", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateDailyStatistics")
    @ResponseWrapper(localName = "activateDailyStatisticsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateDailyStatisticsResponse")
    public void activateDailyStatistics(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockDailyStatistics", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockDailyStatistics")
    @ResponseWrapper(localName = "blockDailyStatisticsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockDailyStatisticsResponse")
    public void blockDailyStatistics(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param dailyQuotaDTO
     * @param principal
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateDailyQuota", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateDailyQuota")
    @ResponseWrapper(localName = "updateDailyQuotaResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateDailyQuotaResponse")
    public void updateDailyQuota(
        @WebParam(name = "dailyQuotaDTO", targetNamespace = "")
        SubscriberDailyQuotaDTO dailyQuotaDTO,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockCollectCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockCollectCalls")
    @ResponseWrapper(localName = "blockCollectCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockCollectCallsResponse")
    public void blockCollectCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockAnonymousCalls", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockAnonymousCalls")
    @ResponseWrapper(localName = "blockAnonymousCallsResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockAnonymousCallsResponse")
    public void blockAnonymousCalls(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param monthlyQuotaDTO
     * @param principal
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateMonthlyQuota", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateMonthlyQuota")
    @ResponseWrapper(localName = "updateMonthlyQuotaResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateMonthlyQuotaResponse")
    public void updateMonthlyQuota(
        @WebParam(name = "monthlyQuotaDTO", targetNamespace = "")
        SubscriberMonthlyQuotaDTO monthlyQuotaDTO,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockSubscriber")
    @ResponseWrapper(localName = "blockSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockSubscriberResponse")
    public void blockSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateSubscriber")
    @ResponseWrapper(localName = "activateSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateSubscriberResponse")
    public void activateSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @param voicemailPassword
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateVoicemail", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateVoicemail")
    @ResponseWrapper(localName = "activateVoicemailResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateVoicemailResponse")
    public void activateVoicemail(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "voicemailPassword", targetNamespace = "")
        Long voicemailPassword,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockVoicemail", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockVoicemail")
    @ResponseWrapper(localName = "blockVoicemailResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockVoicemailResponse")
    public void blockVoicemail(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "removeSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RemoveSubscriber")
    @ResponseWrapper(localName = "removeSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RemoveSubscriberResponse")
    public void removeSubscriber(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns java.lang.Double
     * @throws WSException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "retrieveCredit", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveCredit")
    @ResponseWrapper(localName = "retrieveCreditResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveCreditResponse")
    public Double retrieveCredit(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param obs
     * @param principal
     * @param username
     * @param value
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "addCredit", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.AddCredit")
    @ResponseWrapper(localName = "addCreditResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.AddCreditResponse")
    public void addCredit(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "value", targetNamespace = "")
        Double value,
        @WebParam(name = "obs", targetNamespace = "")
        String obs,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @return
     *     returns java.lang.Integer
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "subscriberId", targetNamespace = "")
    @RequestWrapper(localName = "insertSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.InsertSubscriber")
    @ResponseWrapper(localName = "insertSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.InsertSubscriberResponse")
    public Integer insertSubscriber(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param principal
     * @param subscriber
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubscriber", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriber")
    @ResponseWrapper(localName = "updateSubscriberResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.UpdateSubscriberResponse")
    public void updateSubscriber(
        @WebParam(name = "subscriber", targetNamespace = "")
        SubscriberDTO subscriber,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param actualPassword
     * @param confirmNewPassword
     * @param domain
     * @param newPassword
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "changePasswordWEB", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ChangePasswordWEB")
    @ResponseWrapper(localName = "changePasswordWEBResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ChangePasswordWEBResponse")
    public void changePasswordWEB(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "actualPassword", targetNamespace = "")
        String actualPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param newProfileId
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "changeProfile", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ChangeProfile")
    @ResponseWrapper(localName = "changeProfileResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ChangeProfileResponse")
    public void changeProfile(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "newProfileId", targetNamespace = "")
        Integer newProfileId,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns com.sippulse.soapadapter.sippulse.client.subscriberWS.SubscriberDailyQuotaDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "dailyQuotaDTO", targetNamespace = "")
    @RequestWrapper(localName = "retrieveDailyQuota", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveDailyQuota")
    @ResponseWrapper(localName = "retrieveDailyQuotaResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveDailyQuotaResponse")
    public SubscriberDailyQuotaDTO retrieveDailyQuota(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @return
     *     returns com.sippulse.soapadapter.sippulse.client.subscriberWS.SubscriberMonthlyQuotaDTO
     * @throws WSException
     */
    @WebMethod
    @WebResult(name = "monthlyQuotaDTO", targetNamespace = "")
    @RequestWrapper(localName = "retrieveMonthlyQuotaDTO", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveMonthlyQuotaDTO")
    @ResponseWrapper(localName = "retrieveMonthlyQuotaDTOResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.RetrieveMonthlyQuotaDTOResponse")
    public SubscriberMonthlyQuotaDTO retrieveMonthlyQuotaDTO(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateSoftphone", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateSoftphone")
    @ResponseWrapper(localName = "activateSoftphoneResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateSoftphoneResponse")
    public void activateSoftphone(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "blockSoftphone", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockSoftphone")
    @ResponseWrapper(localName = "blockSoftphoneResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.BlockSoftphoneResponse")
    public void blockSoftphone(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateEntry0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateEntry0303")
    @ResponseWrapper(localName = "activateEntry0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateEntry0303Response")
    public void activateEntry0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "disableValidateSource0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.DisableValidateSource0303")
    @ResponseWrapper(localName = "disableValidateSource0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.DisableValidateSource0303Response")
    public void disableValidateSource0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param domain
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "activateValidateSource0303", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateValidateSource0303")
    @ResponseWrapper(localName = "activateValidateSource0303Response", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ActivateValidateSource0303Response")
    public void activateValidateSource0303(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

    /**
     * 
     * @param actualPassword
     * @param confirmNewPassword
     * @param domain
     * @param newPassword
     * @param principal
     * @param username
     * @throws WSException
     */
    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://service.ws.sippulse.voffice.com.br/", className = "com.sippulse.soapadapter.sippulse.client.subscriberWS.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "domain", targetNamespace = "")
        String domain,
        @WebParam(name = "actualPassword", targetNamespace = "")
        String actualPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "confirmNewPassword", targetNamespace = "")
        String confirmNewPassword,
        @WebParam(name = "principal", targetNamespace = "")
        UserPrincipalDTO principal)
        throws WSException
    ;

}
